
export const ACTIVITY_TYPES = [
    "Curva de abrigos",
    "Instalação de abrigos",
    "Fundação de abrigos",
    "Supressão de abrigos",
    "Curva de totens",
    "Instalação de totens",
    "Fundação de totens",
    "Supressão de totens",
    "Painéis digitais",
    "Painéis estáticos",
    "Manutenção preventiva civil",
    "Manutenção preventiva elétrica",
    "Manutenção corretiva civil",
    "Manutenção corretiva elétrica",
    "Sac cop civil",
    "Sac cop elétrica",
    "Kit elétrico",
    "Ramal",
    "Painéis apagados",
    "Painéis danificados",
    "Projeto especial",
    "Corbucci preventiva",
    "Corbucci corretiva",
    "Vidros",
    "Postes",
    "Pmv",
    "Qmc",
    "Postagens",
    "Eventos",
    "Slack",
    "Vistorias",
    "Cartas",
    "Fiscalização",
    "Area de risco",
    "Outros"
];
