
export const ACTIVITY_TYPES = [
    "Curva de abrigos",
    "Curva de totens",
    "Painéis digitais",
    "Painéis estáticos",
    "Manutenção preventiva civil",
    "Manutenção preventiva elétrica",
    "Manutenção corretiva civil",
    "Manutenção corretiva elétrica",
    "Sac cop civil",
    "Sac cop elétrica",
    "Kit elétrico",
    "Ramal",
    "Painéis apagados",
    "Painéis danificados",
    "Projeto especial",
    "Corbucci preventiva",
    "Corbucci corretiva",
    "Vidros",
    "Postes",
    "Pmv",
    "Qmc",
    "Postagens",
    "Eventos",
    "Slack",
    "Vistorias",
    "Cartas",
    "Fiscalização",
    "Area de risco",
    "Outros"
];
